# Generated by Django 5.1.1 on 2024-09-13 14:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                (
                    'status',
                    models.CharField(
                        choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled')],
                        default='Created',
                        max_length=20
                    )
                ),
                ('authorId', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('approved', models.IntegerField(default=0)),
                (
                    'authorType',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')
                ),
                (
                    'tender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender'
                    )
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BidDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'decision',
                    models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='decisions',
                        to='organizations.employee'
                    )
                ),
                (
                    'bid',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='bids.bid'
                    )
                ),
            ],
        ),
        migrations.CreateModel(
            name='BidReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bid')),
            ],
        ),
        migrations.CreateModel(
            name='BidVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                (
                    'status',
                    models.CharField(
                        choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled')],
                        max_length=20
                    )
                ),
                ('version', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bid')),
            ],
        ),
    ]
